import SwiftUI

extension LocalizedStringKey {
    
    static let aboutApp = LocalizedStringKey("AboutApp")
    static let appName = LocalizedStringKey("AppName")
    static let bringAllToFront = LocalizedStringKey("BringAllToFront")
    static let cancel = LocalizedStringKey("Cancel")
    static let changePasswordAdvice = LocalizedStringKey("ChangePasswordAdvice")
    static let copy = LocalizedStringKey("Copy")
    static let created = LocalizedStringKey("Created")
    static let createPasswordAdvice = LocalizedStringKey("CreatePasswordAdvice")
    static let createVault = LocalizedStringKey("CreateVault")
    static let cut = LocalizedStringKey("Cut")
    static let delete = LocalizedStringKey("Delete")
    static let description = LocalizedStringKey("Description")
    static let edit = LocalizedStringKey("Edit")
    static let enterPassword = LocalizedStringKey("EnterPassword")
    static let file = LocalizedStringKey("File")
    static let generatePassword = LocalizedStringKey("GeneratePassword")
    static let hideApp = LocalizedStringKey("HideApp")
    static let hideOthers = LocalizedStringKey("HideOthers")
    static let iCloud = LocalizedStringKey("iCloud")
    static let iCloudSignUpTitle = LocalizedStringKey("iCloudSignUpTitle")
    static let iCloudSignUpDescription = LocalizedStringKey("iCloudSignUpDescription")
    static let iCloudStatusLoading = LocalizedStringKey("iCloudStatusLoading")
    static let iCloudSyncTitle = LocalizedStringKey("iCloudSyncTitle")
    static let iCloudSyncDescription = LocalizedStringKey("iCloudSyncDescription")
    static let includeUppercase = LocalizedStringKey("IncludeUppercase")
    static let includeDigits = LocalizedStringKey("IncludeDigits")
    static let includeSpecialCharacters = LocalizedStringKey("IncludeSpecialCharacters")
    static let length = LocalizedStringKey("Length")
    static let lock = LocalizedStringKey("Lock")
    static let login = LocalizedStringKey("Login")
    static let masterPassword = LocalizedStringKey("MasterPassword")
    static let minimize = LocalizedStringKey("Minimize")
    static let modified = LocalizedStringKey("Modified")
    static let next = LocalizedStringKey("Next")
    static let noMatches = LocalizedStringKey("NoMatches")
    static let password = LocalizedStringKey("Password")
    static let passwordMismatch = LocalizedStringKey("PasswordMismatch")
    static let paste = LocalizedStringKey("Paste")
    static let pasteMatchStyle = LocalizedStringKey("PasteMatchStyle")
    static let preferences = LocalizedStringKey("Preferences")
    static let quitApp = LocalizedStringKey("QuitApp")
    static let redo = LocalizedStringKey("Redo")
    static let repeatPassword = LocalizedStringKey("RepeatPassword")
    static let reusePasswordAdvice = LocalizedStringKey("ReusePasswordAdvice")
    static let save = LocalizedStringKey("Save")
    static let selectAll = LocalizedStringKey("SelectAll")
    static let showAll = LocalizedStringKey("ShowAll")
    static let title = LocalizedStringKey("Title")
    static let undo = LocalizedStringKey("Undo")
    static let unlockVault = LocalizedStringKey("UnlockVault")
    static let value = LocalizedStringKey("Value")
    static let vaultCreationFailedMessage = LocalizedStringKey("VaultCreationFailedMessage")
    static let view = LocalizedStringKey("View")
    static let window = LocalizedStringKey("Window")
    static let wrongPassword = LocalizedStringKey("WrongPassword")
    static let zoom = LocalizedStringKey("Zoom")
    
}
