import SwiftUI

extension LocalizedStringKey {
    
    static let addItem = LocalizedStringKey("AddItem")
    static let appName = LocalizedStringKey("AppName")
    static let bankCard = LocalizedStringKey("BankCard")
    static let bankCardNamePlaceholder = LocalizedStringKey("BankCardNamePlaceholder")
    static let bankCardTypePlaceholder = LocalizedStringKey("BankCardTypePlaceholder")
    static let bankCardNumberPlaceholder = LocalizedStringKey("BankCardNumberPlaceholder")
    static let bankCardValidityDatePlaceholder = LocalizedStringKey("BankCardValidityDatePlaceholder")
    static let bankCardValidFromPlaceholder = LocalizedStringKey("BankCardValidFromPlaceholder")
    static let bankCardNotePlaceholder = LocalizedStringKey("BankCardNotePlaceholder")
    static let bankCardPinPlaceholder = LocalizedStringKey("BankCardPinPlaceholder")
    static let bankAccount = LocalizedStringKey("BankAccount")
    static let bankAccountName = LocalizedStringKey("BankAccountName")
    static let bankAccountHolder = LocalizedStringKey("BankAccountHolder")
    static let bankAccountCode = LocalizedStringKey("BankAccountCode")
    static let bankAccountNumber = LocalizedStringKey("BankAccountNumber")
    static let bankAccountSwiftCode = LocalizedStringKey("BankAccountSwiftCode")
    static let bankAccountIban = LocalizedStringKey("BankAccountIban")
    static let bankAccountPin = LocalizedStringKey("BankAccountPin")
    static let bankAccountOnlineBankingUrl = LocalizedStringKey("BankAccountOnlineBankingUrl")
    static let bankCardCvvPlaceholder = LocalizedStringKey("BankCardCvvPlaceholder")
    static let biometricActivationFailed = LocalizedStringKey("BiometricActivationFailed")
    static let biometricNotAvailable = LocalizedStringKey("BiometricNotAvailable")
    static let biometricNotEnrolled = LocalizedStringKey("BiometricNotEnrolled")
    static let cancel = LocalizedStringKey("Cancel")
    static let changeMasterPassword = LocalizedStringKey("ChangeMasterPassword")
    static let changePasswordAdvice = LocalizedStringKey("ChangePasswordAdvice")
    static let chooseItemType = LocalizedStringKey("ChooseItemType")
    static let copy = LocalizedStringKey("Copy")
    static let created = LocalizedStringKey("Created")
    static let createPasswordAdvice = LocalizedStringKey("CreatePasswordAdvice")
    static let createVault = LocalizedStringKey("CreateVault")
    static let currentMasterPassword = LocalizedStringKey("CurrentMasterPassword")
    static let customField = LocalizedStringKey("CustomField")
    static let customFieldName = LocalizedStringKey("CustomFieldName")
    static let customFieldValue = LocalizedStringKey("CustomFieldValue")
    static let cut = LocalizedStringKey("Cut")
    static let delete = LocalizedStringKey("Delete")
    static let deleteFailed = LocalizedStringKey("DeleteFailed")
    static let description = LocalizedStringKey("Description")
    static let edit = LocalizedStringKey("Edit")
    static let enable = LocalizedStringKey("Enable")
    static let enableBiometricUnlockDescription = LocalizedStringKey("EnableBiometricUnlockDescription")
    static let enterPassword = LocalizedStringKey("EnterPassword")
    static let file = LocalizedStringKey("File")
    static let fileName = LocalizedStringKey("FileName")
    static let generatePassword = LocalizedStringKey("GeneratePassword")
    static let iCloud = LocalizedStringKey("iCloud")
    static let iCloudSignUpTitle = LocalizedStringKey("iCloudSignUpTitle")
    static let iCloudSignUpDescription = LocalizedStringKey("iCloudSignUpDescription")
    static let iCloudStatusLoading = LocalizedStringKey("iCloudStatusLoading")
    static let iCloudSyncTitle = LocalizedStringKey("iCloudSyncTitle")
    static let iCloudSyncDescription = LocalizedStringKey("iCloudSyncDescription")
    static let includeUppercase = LocalizedStringKey("IncludeUppercase")
    static let includeDigits = LocalizedStringKey("IncludeDigits")
    static let includeSpecialCharacters = LocalizedStringKey("IncludeSpecialCharacters")
    static let invalidCurrentPassword = LocalizedStringKey("InvalidCurrentPassword")
    static let length = LocalizedStringKey("Length")
    static let loadFailed = LocalizedStringKey("LoadFailed")
    static let login = LocalizedStringKey("Login")
    static let masterPassword = LocalizedStringKey("MasterPassword")
    static let masterPasswordChangeDidFail = LocalizedStringKey("MasterPasswordChangeDidFail")
    static let modified = LocalizedStringKey("Modified")
    static let newMasterPassword = LocalizedStringKey("NewMasterPassword")
    static let next = LocalizedStringKey("Next")
    static let noMatches = LocalizedStringKey("NoMatches")
    static let note = LocalizedStringKey("Note")
    static let notePlaceholder = LocalizedStringKey("NotePlaceholder")
    static let password = LocalizedStringKey("Password")
    static let passwordMismatch = LocalizedStringKey("PasswordMismatch")
    static let paste = LocalizedStringKey("Paste")
    static let pasteMatchStyle = LocalizedStringKey("PasteMatchStyle")
    static let redo = LocalizedStringKey("Redo")
    static let repeatPassword = LocalizedStringKey("RepeatPassword")
    static let repeatNewPassword = LocalizedStringKey("RepeatNewPassword")
    static let retry = LocalizedStringKey("Retry")
    static let reusePasswordAdvice = LocalizedStringKey("ReusePasswordAdvice")
    static let save = LocalizedStringKey("Save")
    static let saveFailed = LocalizedStringKey("SaveFailed")
    static let search = LocalizedStringKey("Search")
    static let selectAll = LocalizedStringKey("SelectAll")
    static let title = LocalizedStringKey("Title")
    static let undo = LocalizedStringKey("Undo")
    static let unlockVault = LocalizedStringKey("UnlockVault")
    static let url = LocalizedStringKey("URL")
    static let useBiometricUnlock = LocalizedStringKey("UseBiometricUnlock")
    static let user = LocalizedStringKey("User")
    static let value = LocalizedStringKey("Value")
    static let vault = LocalizedStringKey("Vault")
    static let vaultCreationFailed = LocalizedStringKey("VaultCreationFailed")
    static let view = LocalizedStringKey("View")
    static let wrongPassword = LocalizedStringKey("WrongPassword")
    static let wifi = LocalizedStringKey("Wifi")
    static let wifiNetworkName = LocalizedStringKey("WifiNetworkName")
    static let wifiNetworkPassword = LocalizedStringKey("WifiNetworkPassword")
    
}

extension String {
    
    static let aboutApp = NSLocalizedString("AboutApp", comment: "")
    static let bringAllToFront = NSLocalizedString("BringAllToFront", comment: "")
    static let hideApp = NSLocalizedString("HideApp", comment: "")
    static let hideOthers = NSLocalizedString("HideOthers", comment: "")
    static let lock = NSLocalizedString("Lock", comment: "")
    static let minimize = NSLocalizedString("Minimize", comment: "")
    static let preferences = NSLocalizedString("Preferences", comment: "")
    static let quitApp = NSLocalizedString("QuitApp", comment: "")
    static let showAll = NSLocalizedString("ShowAll", comment: "")
    static let window = NSLocalizedString("Window", comment: "")
    static let zoom = NSLocalizedString("Zoom", comment: "")
    
}
