name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  test:
    name: Run tests
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Crypto package
        run: xcodebuild test -quiet -scheme 'Crypto'
      - name: Test Pasteboard package
        run: xcodebuild test -quiet -scheme 'Pasteboard'
      - name: Test Preferences package
        run: xcodebuild test -quiet -scheme 'Preferences'
      - name: Test Search package
        run: xcodebuild test -quiet -scheme 'Search'
      - name: Test Store package
        run: xcodebuild test -quiet -scheme 'Store'
