name: Continuous Integration
on: pull_request
jobs:
  test:
    name: Run tests
    runs-on: macos-10.15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test crypto package
      run: xcodebuild test -quiet -target 'Vault macOS' -scheme 'Crypto'
