name: Continuous Integration
on: pull_request
jobs:
  test:
    name: Run Tests
    runs-on: macos-10.15
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Test Crypto Package
      run: xcodebuild test -target 'Vault macOS' -scheme 'Crypto'
