name: Integrate
on:
  - pull_request
  
jobs:
  test:
    name: Run tests
    runs-on: macos-11.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: Running tests
        run: xcodebuild test -scheme iOS -destination 'platform=iOS Simulator,name=iPhone 12'
