name: Integrate
on: workflow_dispatch
  
jobs:
  test:
    name: Run tests
    runs-on: macos-11.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Select Xcode version
        run: ls /Applications
      - name: Test Pasteboard package
        run: xcodebuild test -quiet -scheme 'Pasteboard'
